name: EAS Build

on:
    push:
        branches: ['release', 'pre-release']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository code
            - name: Checkout code
              uses: actions/checkout@v4

            # Set up Bun
            - name: Set up Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            # Install dependencies
            - name: Install dependencies
              run: bun install --frozen-lockfile

            # Setup Expo and EAS
            - name: Setup Expo and EAS
              uses: expo/expo-github-action@v8
              with:
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}

            # EAS build
            - name: Run EAS build
              run: eas build --profile preview --platform android --local --output ./artifacts

            # Upload artifact as apk
            - name: Rename APK file
              run: mv artifacts artifacts.apk

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: android-apk
                  path: artifacts.apk
