name: EAS_BUILD_LOCAL

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Bun
    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    # Install dependencies
    - name: Install dependencies
      run: bun install --frozen-lockfile

    # Install EAS CLI
    - name: Install EAS CLI
      run: bun add -g @expo/eas-cli

    # Run EAS build
    - name: Run EAS build
      run: eas build --profile preview --platform android --local
